title: AI 
tagline: Autonomous

author:
  name: Jim 
  url: https://www.facebook.com/profile.php?id=100001271065926

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

paginate: 3

tags_path: /tags/
categories_path: /categories/

remote_theme: zivong/jekyll-theme-hydure
#theme: jekyll-theme-hydure
